services:
  tarefas:
    build:
      context: .
    ports:
      - '80:8000'
    command: "-e main:APP"

  notificacao:
    build:
      context: .
    ports:
      - '81:8000'
    command: "-e notificacao:APP_NOTIFICACAO"